# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: drtapiavargas@gmail.com
author_name: Dr. Ignacio Tapia Vargas
ide_jetbrains: false
ide_vscode: true
preset_name: custom
project_name: fibonacci-frontend
use_eslint_prettier: false
use_github_actions: false
use_jest: false
use_playwright: false
use_tailwind: false

